import { CellData, FormulaHelp, Sheet } from '../types';
import { recalculateSheet } from './formulaEngine';

export const EXCEL_FUNCTIONS: FormulaHelp[] = [
  {
    name: 'SUM',
    syntax: 'SUM(number1, [number2], ...)',
    category: 'Math',
    descriptionFa: 'محاسبه مجموع اعداد، خانه‌ها یا محدوده‌های مشخص شده',
    descriptionEn: 'Adds all the numbers in a range of cells',
    example: '=SUM(B2:B10)',
  },
  {
    name: 'AVERAGE',
    syntax: 'AVERAGE(number1, [number2], ...)',
    category: 'Statistical',
    descriptionFa: 'محاسبه میانگین (معدل) حسابی مقادیر در محدوده',
    descriptionEn: 'Returns the average (arithmetic mean) of its arguments',
    example: '=AVERAGE(C2:C20)',
  },
  {
    name: 'COUNT',
    syntax: 'COUNT(value1, [value2], ...)',
    category: 'Statistical',
    descriptionFa: 'شمارش تعداد خانه‌های دارای مقدار عددی',
    descriptionEn: 'Counts how many numbers are in the list of arguments',
    example: '=COUNT(A2:A100)',
  },
  {
    name: 'COUNTA',
    syntax: 'COUNTA(value1, [value2], ...)',
    category: 'Statistical',
    descriptionFa: 'شمارش تعداد خانه‌های غیرخالی (متن یا عدد)',
    descriptionEn: 'Counts the number of cells that are not empty',
    example: '=COUNTA(B2:B50)',
  },
  {
    name: 'MIN',
    syntax: 'MIN(number1, [number2], ...)',
    category: 'Statistical',
    descriptionFa: 'یافتن کمترین مقدار در میان مجموعه اعداد',
    descriptionEn: 'Returns the smallest number in a set of values',
    example: '=MIN(D2:D15)',
  },
  {
    name: 'MAX',
    syntax: 'MAX(number1, [number2], ...)',
    category: 'Statistical',
    descriptionFa: 'یافتن بیشترین مقدار در میان مجموعه اعداد',
    descriptionEn: 'Returns the largest number in a set of values',
    example: '=MAX(D2:D15)',
  },
  {
    name: 'IF',
    syntax: 'IF(logical_test, value_if_true, value_if_false)',
    category: 'Logical',
    descriptionFa: 'بررسی شرط و بازگرداندن مقدار دلخواه در صورت درست یا نادرست بودن',
    descriptionEn: 'Specifies a logical test to perform',
    example: '=IF(E2>=10, "قبول", "مردود")',
  },
  {
    name: 'SUMIF',
    syntax: 'SUMIF(range, criteria, [sum_range])',
    category: 'Math',
    descriptionFa: 'جمع زدن خانه‌هایی که شرط خاصی را برآورده می‌کنند',
    descriptionEn: 'Adds the cells specified by a given condition or criteria',
    example: '=SUMIF(C2:C20, ">1000", D2:D20)',
  },
  {
    name: 'COUNTIF',
    syntax: 'COUNTIF(range, criteria)',
    category: 'Statistical',
    descriptionFa: 'شمارش خانه‌هایی که شرط مورد نظر را دارند',
    descriptionEn: 'Counts the number of cells within a range that meet the given criteria',
    example: '=COUNTIF(E2:E20, "تکمیل شده")',
  },
  {
    name: 'ROUND',
    syntax: 'ROUND(number, num_digits)',
    category: 'Math',
    descriptionFa: 'گرد کردن عدد به تعداد ارقام اعشار مشخص',
    descriptionEn: 'Rounds a number to a specified number of digits',
    example: '=ROUND(A1, 2)',
  },
  {
    name: 'VLOOKUP',
    syntax: 'VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])',
    category: 'Lookup',
    descriptionFa: 'جستجوی عمودی مقدار در ستون اول جدول و بازگرداندن مقدار ستون متناظر',
    descriptionEn: 'Looks for a value in the leftmost column of a table',
    example: '=VLOOKUP("کالای ۱", A2:D10, 3, FALSE)',
  },
  {
    name: 'CONCAT',
    syntax: 'CONCAT(text1, [text2], ...)',
    category: 'Text',
    descriptionFa: 'ترکیب و اتصال چندین رشته متنی به یکدیگر',
    descriptionEn: 'Combines the text from multiple ranges and/or strings',
    example: '=CONCAT(A2, " ", B2)',
  },
  {
    name: 'UPPER',
    syntax: 'UPPER(text)',
    category: 'Text',
    descriptionFa: 'تبدیل تمام حروف انگلیسی متن به حروف بزرگ',
    descriptionEn: 'Converts text to uppercase',
    example: '=UPPER(A2)',
  },
  {
    name: 'LOWER',
    syntax: 'LOWER(text)',
    category: 'Text',
    descriptionFa: 'تبدیل حروف متن به حروف کوچک',
    descriptionEn: 'Converts text to lowercase',
    example: '=LOWER(A2)',
  },
  {
    name: 'TRIM',
    syntax: 'TRIM(text)',
    category: 'Text',
    descriptionFa: 'حذف فاصله‌های اضافی در ابتدا و انتهای متن',
    descriptionEn: 'Removes all spaces from text except for single spaces between words',
    example: '=TRIM(A2)',
  },
  {
    name: 'TODAY',
    syntax: 'TODAY()',
    category: 'Date',
    descriptionFa: 'درج تاریخ امروز به صورت پویا',
    descriptionEn: 'Returns the serial number of the current date',
    example: '=TODAY()',
  },
  {
    name: 'NOW',
    syntax: 'NOW()',
    category: 'Date',
    descriptionFa: 'درج تاریخ و ساعت فعلی سیستم',
    descriptionEn: 'Returns the current date and time',
    example: '=NOW()',
  },
];

export function createEmptySheet(id: string, name: string, isRTL = true): Sheet {
  return {
    id,
    name,
    cells: {},
    colWidths: {},
    rowHeights: {},
    showGridLines: true,
    showHeaders: true,
    isRTL,
    tabColor: '#107c41',
  };
}

export function createBudgetTemplate(): Sheet {
  const cells: Record<string, CellData> = {
    A1: { raw: 'گزارش بودجه و هزینه‌های ماهانه', bold: true, fontSize: 16, textColor: '#0f5132', bgColor: '#d1e7dd', align: 'center' },
    B1: { raw: '', bgColor: '#d1e7dd' },
    C1: { raw: '', bgColor: '#d1e7dd' },
    D1: { raw: '', bgColor: '#d1e7dd' },
    E1: { raw: '', bgColor: '#d1e7dd' },
    F1: { raw: '', bgColor: '#d1e7dd' },

    A2: { raw: 'ردیف', bold: true, bgColor: '#198754', textColor: '#ffffff', align: 'center' },
    B2: { raw: 'شرح هزینه', bold: true, bgColor: '#198754', textColor: '#ffffff', align: 'center' },
    C2: { raw: 'دسته‌بندی', bold: true, bgColor: '#198754', textColor: '#ffffff', align: 'center' },
    D2: { raw: 'پیش‌بینی بودجه', bold: true, bgColor: '#198754', textColor: '#ffffff', align: 'center' },
    E2: { raw: 'هزینه واقعی', bold: true, bgColor: '#198754', textColor: '#ffffff', align: 'center' },
    F2: { raw: 'انحراف / اختلاف', bold: true, bgColor: '#198754', textColor: '#ffffff', align: 'center' },

    A3: { raw: '1', align: 'center' },
    B3: { raw: 'اجاره بها و مسکن', align: 'right' },
    C3: { raw: 'ثابت', align: 'center' },
    D3: { raw: '15000000', format: 'number', align: 'left' },
    E3: { raw: '15000000', format: 'number', align: 'left' },
    F3: { raw: '=D3-E3', format: 'number', align: 'left', bold: true },

    A4: { raw: '2', align: 'center' },
    B4: { raw: 'اقلام خوراکی و سوپرمارکت', align: 'right' },
    C4: { raw: 'متغیر', align: 'center' },
    D4: { raw: '8000000', format: 'number', align: 'left' },
    E4: { raw: '8650000', format: 'number', align: 'left' },
    F4: { raw: '=D4-E4', format: 'number', align: 'left', bold: true, textColor: '#dc3545' },

    A5: { raw: '3', align: 'center' },
    B5: { raw: 'قبوض آب، برق، گاز و اینترنت', align: 'right' },
    C5: { raw: 'ثابت', align: 'center' },
    D5: { raw: '1800000', format: 'number', align: 'left' },
    E5: { raw: '1620000', format: 'number', align: 'left' },
    F5: { raw: '=D5-E5', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A6: { raw: '4', align: 'center' },
    B6: { raw: 'رفت و آمد و بنزین', align: 'right' },
    C6: { raw: 'متغیر', align: 'center' },
    D6: { raw: '3000000', format: 'number', align: 'left' },
    E6: { raw: '2800000', format: 'number', align: 'left' },
    F6: { raw: '=D6-E6', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A7: { raw: '5', align: 'center' },
    B7: { raw: 'تفریح و رستوران', align: 'right' },
    C7: { raw: 'اختیاری', align: 'center' },
    D7: { raw: '4000000', format: 'number', align: 'left' },
    E7: { raw: '4500000', format: 'number', align: 'left' },
    F7: { raw: '=D7-E7', format: 'number', align: 'left', bold: true, textColor: '#dc3545' },

    A8: { raw: '6', align: 'center' },
    B8: { raw: 'پوشاک و خرید شخصی', align: 'right' },
    C8: { raw: 'اختیاری', align: 'center' },
    D8: { raw: '2500000', format: 'number', align: 'left' },
    E8: { raw: '2100000', format: 'number', align: 'left' },
    F8: { raw: '=D8-E8', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A9: { raw: 'جمع کل', bold: true, bgColor: '#e9ecef', align: 'center' },
    B9: { raw: '', bgColor: '#e9ecef' },
    C9: { raw: '', bgColor: '#e9ecef' },
    D9: { raw: '=SUM(D3:D8)', bold: true, bgColor: '#e9ecef', format: 'number', align: 'left' },
    E9: { raw: '=SUM(E3:E8)', bold: true, bgColor: '#e9ecef', format: 'number', align: 'left' },
    F9: { raw: '=SUM(F3:F8)', bold: true, bgColor: '#e9ecef', format: 'number', align: 'left' },

    A11: { raw: 'میانگین هزینه اقلام:', bold: true },
    B11: { raw: '=AVERAGE(E3:E8)', format: 'number', bold: true },
    A12: { raw: 'بیشترین رقم هزینه:', bold: true },
    B12: { raw: '=MAX(E3:E8)', format: 'number', bold: true },
  };

  const recalculated = recalculateSheet(cells);

  return {
    id: 'sheet_budget',
    name: 'بودجه ماهانه',
    cells: recalculated,
    colWidths: { 0: 60, 1: 220, 2: 120, 3: 130, 4: 130, 5: 140 },
    rowHeights: { 1: 36, 2: 30 },
    tabColor: '#198754',
    isRTL: true,
  };
}

export function createSalesTemplate(): Sheet {
  const cells: Record<string, CellData> = {
    A1: { raw: 'گزارش فروش و سود ناخالص فصلی', bold: true, fontSize: 16, textColor: '#084298', bgColor: '#cfe2ff', align: 'center' },
    B1: { raw: '', bgColor: '#cfe2ff' },
    C1: { raw: '', bgColor: '#cfe2ff' },
    D1: { raw: '', bgColor: '#cfe2ff' },
    E1: { raw: '', bgColor: '#cfe2ff' },
    F1: { raw: '', bgColor: '#cfe2ff' },
    G1: { raw: '', bgColor: '#cfe2ff' },

    A2: { raw: 'کد', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },
    B2: { raw: 'نام محصول', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },
    C2: { raw: 'تعداد فروش', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },
    D2: { raw: 'قیمت فروش (تومان)', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },
    E2: { raw: 'فروش کل', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },
    F2: { raw: 'بهای تمام شده', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },
    G2: { raw: 'سود ناخالص', bold: true, bgColor: '#0d6efd', textColor: '#ffffff', align: 'center' },

    A3: { raw: 'P101', align: 'center' },
    B3: { raw: 'لپ‌تاپ گیمینگ ایسوس', align: 'right' },
    C3: { raw: '12', align: 'center' },
    D3: { raw: '62000000', format: 'number', align: 'left' },
    E3: { raw: '=C3*D3', format: 'number', align: 'left' },
    F3: { raw: '52000000', format: 'number', align: 'left' },
    G3: { raw: '=E3-(C3*F3)', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A4: { raw: 'P102', align: 'center' },
    B4: { raw: 'مانیتور ۲۷ اینچ ۴K', align: 'right' },
    C4: { raw: '35', align: 'center' },
    D4: { raw: '18500000', format: 'number', align: 'left' },
    E4: { raw: '=C4*D4', format: 'number', align: 'left' },
    F4: { raw: '14800000', format: 'number', align: 'left' },
    G4: { raw: '=E4-(C4*F4)', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A5: { raw: 'P103', align: 'center' },
    B5: { raw: 'کیبورد مکانیکی وایرلس', align: 'right' },
    C5: { raw: '80', align: 'center' },
    D5: { raw: '4200000', format: 'number', align: 'left' },
    E5: { raw: '=C5*D5', format: 'number', align: 'left' },
    F5: { raw: '3100000', format: 'number', align: 'left' },
    G5: { raw: '=E5-(C5*F5)', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A6: { raw: 'P104', align: 'center' },
    B6: { raw: 'هدفون نویزکنسلینگ سونی', align: 'right' },
    C6: { raw: '42', align: 'center' },
    D6: { raw: '16000000', format: 'number', align: 'left' },
    E6: { raw: '=C6*D6', format: 'number', align: 'left' },
    F6: { raw: '12800000', format: 'number', align: 'left' },
    G6: { raw: '=E6-(C6*F6)', format: 'number', align: 'left', bold: true, textColor: '#198754' },

    A7: { raw: 'مجموع کل', bold: true, bgColor: '#e2e3e5', align: 'center' },
    B7: { raw: '', bgColor: '#e2e3e5' },
    C7: { raw: '=SUM(C3:C6)', bold: true, bgColor: '#e2e3e5', align: 'center' },
    D7: { raw: '', bgColor: '#e2e3e5' },
    E7: { raw: '=SUM(E3:E6)', bold: true, bgColor: '#e2e3e5', format: 'number', align: 'left' },
    F7: { raw: '', bgColor: '#e2e3e5' },
    G7: { raw: '=SUM(G3:G6)', bold: true, bgColor: '#e2e3e5', format: 'number', align: 'left' },
  };

  return {
    id: 'sheet_sales',
    name: 'فروش و سود',
    cells: recalculateSheet(cells),
    colWidths: { 0: 60, 1: 200, 2: 90, 3: 140, 4: 140, 5: 140, 6: 140 },
    rowHeights: { 1: 36, 2: 30 },
    tabColor: '#0d6efd',
    isRTL: true,
  };
}

export function createGradebookTemplate(): Sheet {
  const cells: Record<string, CellData> = {
    A1: { raw: 'کارنامه تحصیلی دانش‌آموزان سال تحصیلی', bold: true, fontSize: 16, textColor: '#491217', bgColor: '#f8d7da', align: 'center' },
    B1: { raw: '', bgColor: '#f8d7da' },
    C1: { raw: '', bgColor: '#f8d7da' },
    D1: { raw: '', bgColor: '#f8d7da' },
    E1: { raw: '', bgColor: '#f8d7da' },
    F1: { raw: '', bgColor: '#f8d7da' },
    G1: { raw: '', bgColor: '#f8d7da' },
    H1: { raw: '', bgColor: '#f8d7da' },

    A2: { raw: 'ردیف', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    B2: { raw: 'نام دانش‌آموز', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    C2: { raw: 'ریاضی', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    D2: { raw: 'فیزیک', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    E2: { raw: 'شیمی', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    F2: { raw: 'ادبیات', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    G2: { raw: 'معدل', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },
    H2: { raw: 'وضعیت قبولی', bold: true, bgColor: '#dc3545', textColor: '#ffffff', align: 'center' },

    A3: { raw: '1', align: 'center' },
    B3: { raw: 'علی رضایی', align: 'right' },
    C3: { raw: '18.5', align: 'center' },
    D3: { raw: '17', align: 'center' },
    E3: { raw: '19', align: 'center' },
    F3: { raw: '16.5', align: 'center' },
    G3: { raw: '=ROUND(AVERAGE(C3:F3), 2)', align: 'center', bold: true },
    H3: { raw: '=IF(G3>=12, "قبول", "مردود")', align: 'center', bold: true, textColor: '#198754' },

    A4: { raw: '2', align: 'center' },
    B4: { raw: 'سارا محمدی', align: 'right' },
    C4: { raw: '19.75', align: 'center' },
    D4: { raw: '20', align: 'center' },
    E4: { raw: '19.5', align: 'center' },
    F4: { raw: '19', align: 'center' },
    G4: { raw: '=ROUND(AVERAGE(C4:F4), 2)', align: 'center', bold: true },
    H4: { raw: '=IF(G4>=12, "قبول", "مردود")', align: 'center', bold: true, textColor: '#198754' },

    A5: { raw: '3', align: 'center' },
    B5: { raw: 'مهدی کریمی', align: 'right' },
    C5: { raw: '11', align: 'center' },
    D5: { raw: '10.5', align: 'center' },
    E5: { raw: '12', align: 'center' },
    F5: { raw: '14', align: 'center' },
    G5: { raw: '=ROUND(AVERAGE(C5:F5), 2)', align: 'center', bold: true },
    H5: { raw: '=IF(G5>=12, "قبول", "مردود")', align: 'center', bold: true, textColor: '#ffc107' },

    A6: { raw: '4', align: 'center' },
    B6: { raw: 'نرگس حسینی', align: 'right' },
    C6: { raw: '9.5', align: 'center' },
    D6: { raw: '8', align: 'center' },
    E6: { raw: '11', align: 'center' },
    F6: { raw: '13.5', align: 'center' },
    G6: { raw: '=ROUND(AVERAGE(C6:F6), 2)', align: 'center', bold: true },
    H6: { raw: '=IF(G6>=12, "قبول", "مردود")', align: 'center', bold: true, textColor: '#dc3545' },

    A7: { raw: 'میانگین کل کلاس', bold: true, bgColor: '#f8f9fa', align: 'center' },
    B7: { raw: '', bgColor: '#f8f9fa' },
    C7: { raw: '=ROUND(AVERAGE(C3:C6), 2)', bold: true, align: 'center' },
    D7: { raw: '=ROUND(AVERAGE(D3:D6), 2)', bold: true, align: 'center' },
    E7: { raw: '=ROUND(AVERAGE(E3:E6), 2)', bold: true, align: 'center' },
    F7: { raw: '=ROUND(AVERAGE(F3:F6), 2)', bold: true, align: 'center' },
    G7: { raw: '=ROUND(AVERAGE(G3:G6), 2)', bold: true, align: 'center', bgColor: '#e9ecef' },
    H7: { raw: '', bgColor: '#f8f9fa' },
  };

  return {
    id: 'sheet_gradebook',
    name: 'کارنامه تحصیلی',
    cells: recalculateSheet(cells),
    colWidths: { 0: 60, 1: 170, 2: 90, 3: 90, 4: 90, 5: 90, 6: 100, 7: 120 },
    rowHeights: { 1: 36, 2: 30 },
    tabColor: '#dc3545',
    isRTL: true,
  };
}
